### PR TITLE
This moves away from ngrok to cloudflare tunnels as they are simpler to launch (IE no account needed)

### PR DESCRIPTION
**Pull request by opencoca**

### CODE REVIEW

**Comment by blueturtleai** [comment]
First of all many thanks for the PR! I had a look at the different changes you suggested and here are my comments:

### Cloudflare instead of Ngrok
I had a look what Cloudflare writes about their free service:

"_We don’t guarantee any SLA or uptime of TryCloudflare - we plan to test new Cloudflare Tunnel features and improvements on these free tunnels. This provides us with a group of connections to test before we deploy to production customers. Free tunnels are meant to be used for testing and development, not for deploying a production website._" https://developers.cloudflare.com/cloudflare-one/connections/connect-apps/do-more-with-tunnels/trycloudflare/

Tbh for me this doesn't sound like a reliable service, which I'd like to use. For that reason I will stick with Ngrok.

But I will change the plugin and switch to https like you did it. Additionally I will add some headers like you proposed. So it will be possible to use the plugin with other tunnel providers if someone likes to do this.

### Checkpoint files from other sources than Huggingface
Huggingface is the only official and legal provider of the checkpoint files. To download the files it's necessary to accept their terms. I know, that there are other unofficial sources for these files. But I don't like to support downloading from them.

### Examples
I don't like to add examples, because I don't want to risk any legal issues. Like "you used this or that artist and this isn't allowed".

**Comment by opencoca** [comment]
According to the license, we're specifically allowed to re-distribute the model and only need to include the same restrictions. 

https://huggingface.co/blog/stable_diffusion#license
 
"You may re-distribute the weights and use the model commercially and/or as a service. If you do, please be aware you have to include the same use restrictions as the ones in the license and share a copy of the CreativeML OpenRAIL-M to all your users."

I'm going to simplify this process.

**Comment by blueturtleai** [comment]
Everybody else uses either the huggingface token and downloads directly from there in their package or just tells users to download the files themselves from huggingface. This is for a simple reason: nobody wants to run into legal issues. I'm no different.

So, I'm sorry, but I won't accept this PR.

**Comment by blueturtleai** [comment]
I switched now from ngrok to cloudflare because several users reported problems connecting to ngrok. Thanks for suggesting this @opencoca! I hope, that cloudflare works with less problems :).

**Comment by blueturtleai** [comment]
Now the model files are directly downloaded from huggingface to google drive (using huggingface username and access token). This takes away the pain of uploading a 4gb file.

**Pull request closed without merging**
